esphome:
  name: smlight-ac
  friendly_name: Klimatizace Airwell

# HW konfigurace pro ESP8266 (standardní čip v SLWF-01)
esp8266:
  board: esp12e

wifi:
  ssid: "NÁZEV_VAŠÍ_WIFI"
  password: "HESLO_VAŠÍ_WIFI"
  ap:
    ssid: "AC-wifi-Airwell"
    password: "slwf01pro"

mdns:
  disabled: false

web_server:
  port: 80
  version: 2

api:

ota:
  - platform: esphome

# UART komunikace s vnitřní deskou klimatizace Airwell / Midea
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

climate:
  - platform: midea_ac
    name: "Klimatizace"
    id: airwell_ac
    beeper: true

# Virtuální spínač s HTTP endpointem pro spínání z FVE / SDG
switch:
  - platform: template
    name: "Shelly Rele Ovladani"
    id: shelly_relay_0
    optimistic: true
    assumed_state: true
    turn_on_action:
      - climate.control:
          id: airwell_ac
          mode: COOL
          target_temperature: 23 °C
    turn_off_action:
      - climate.control:
          id: airwell_ac
          mode: 'OFF'
