name: Build ESPHome Firmware
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ESPHome binary
        uses: esphome/build-action@v2
        with:
          yaml_file: smlight.yaml
          version: latest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .esphome/build/smlight-ac/firmware.bin
